# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170613_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 22, 39, 20, 22838, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 13, 22, 39, 20, 22338, tzinfo=utc)),
        ),
    ]
